sonar.organization=REPLACE_ME_ORG
sonar.projectKey=REPLACE_ME_ORG_phoenix-payment-service

sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src/tests

sonar.exclusions=node_modules/**,coverage/**,**/*.test.js,**/*.spec.js
sonar.test.inclusions=src/tests/**/*.js

# Jest coverage (LCOV)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

